name: Defender Tests

on:
  workflow_dispatch: 
  pull_request:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  actions: read
  security-events: write  # required for SARIF upload to code scanning
  id-token: write 

jobs:
  scan-image:
    runs-on: ubuntu-latest
    
    env:
      GITHUB_REPOSITORY_OWNER_ID: ${{ github.repository_owner_id }}
      GITHUB_REPOSITORY_ID: ${{ github.repository_id }}

    steps:
      - name: Print GitHub-provided environment variables
        run: |
          env | sort | grep -E '^(GITHUB_|RUNNER_|CI=)'
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Defender CLI
        run: |
          curl -L -o defender "https://cli.dfd.security.stage.azure-test.net/public/v2/latest/Defender_linux-x64"
          chmod +x defender

      - name: Scan FS
        shell: bash
        run: |
          ./defender scan fs .
